"""add subscription table

Revision ID: 327f80a3dd7c
Revises: 48cf3d03646a
Create Date: 2026-04-21 19:02:35.102627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327f80a3dd7c'
down_revision: Union[str, Sequence[str], None] = '48cf3d03646a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_unique_constraint(None, 'organizations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    # ### end Alembic commands ###
