"""fix subscription column names

Revision ID: d64e1a286828
Revises: 327f80a3dd7c
Create Date: 2026-04-22 14:44:29.408694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd64e1a286828'
down_revision: Union[str, Sequence[str], None] = '327f80a3dd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('subscriptions', 'update_at')
    op.drop_column('subscriptions', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    # ### end Alembic commands ###
